# Generated by Django 4.2.6 on 2023-10-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bunnyapp.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('kilometers', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bunnyapp.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.IntegerField()),
                ('hunger', models.IntegerField()),
                ('kilometers', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bunnyapp.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Burrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bunnyapp.forest')),
            ],
        ),
    ]
