# Generated by Django 4.2.6 on 2023-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnyapp', '0002_hunter_message_rabbit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest',
            name='message',
            field=models.CharField(default='None', max_length=24),
        ),
    ]
