# Generated by Django 4.2.6 on 2023-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnyapp', '0003_forest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='burrow',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forest',
            name='message',
            field=models.CharField(default='', max_length=24),
        ),
    ]
